basePath: /
definitions:
  cloud_storage.Node:
    properties:
      children:
        items:
          $ref: '#/definitions/cloud_storage.Node'
        type: array
      create_date:
        type: string
      id:
        type: integer
      name:
        type: string
      server_name:
        type: string
      size:
        type: integer
      type:
        type: string
    type: object
  cloud_storage.User:
    properties:
      login:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  cloud_storage.UserInfo:
    properties:
      available_memory:
        type: integer
      id:
        type: integer
      login:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  handler.jsonResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      size:
        type: integer
      status:
        type: string
    type: object
  handler.signInInput:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for CloudStorage Application
  title: Cloud Storage
  version: "1.0"
paths:
  /api/directory:
    get:
      consumes:
      - application/json
      description: get main directory
      operationId: get-main-directory
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cloud_storage.Node'
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get Main Directory
      tags:
      - Directory
  /api/directory/{id}:
    delete:
      consumes:
      - application/json
      description: delete directory
      operationId: delete-directory
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Delete Directory
      tags:
      - Directory
    get:
      consumes:
      - application/json
      description: get directory
      operationId: get-directory
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cloud_storage.Node'
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get Directory
      tags:
      - Directory
    post:
      consumes:
      - application/json
      description: create directory
      operationId: create-directory
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Create Directory
      tags:
      - Directory
  /api/file/{id}:
    delete:
      consumes:
      - application/json
      description: delete file
      operationId: delete-file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Delete File
      tags:
      - File
    get:
      consumes:
      - application/json
      description: download file
      operationId: download-file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Download File
      tags:
      - File
    post:
      consumes:
      - multipart/form-data
      description: upload file
      operationId: upload-file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.jsonResponse'
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Upload File
      tags:
      - File
  /api/user/:
    get:
      consumes:
      - application/json
      description: get user
      operationId: get-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cloud_storage.UserInfo'
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get User
      tags:
      - User
  /api/user/id:
    post:
      consumes:
      - application/json
      description: share object
      operationId: share-object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Share Object
      tags:
      - User
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: SignIn
      tags:
      - auth
  /auth/sing-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/cloud_storage.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: SingUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
